Another breakthrough
Add Arm platform, pointers, global varieties, scaling offsets, arrays, char str literals, more operators, design locals, function params, function arguments, prototypes, testing errors and runtime flags

diff --git a/tests/runtestsn b/tests/runtestsn
--- a/tests/runtestsn
+++ b/tests/runtestsn
@@ -2,26 +2,59 @@
 # Run each test and compare
 # against known good output
 
+# Build our compiler if needed
 if [ ! -f ../compn ]
-then echo "Need to build ../compn first!"; exit 1
+then (cd ..; make)
 fi
 
-for i in input*
-do if [ ! -f "out.$i" ]
+# Try to use each input source file
+for i in input*c
+# We can't do anything if there's no file to test against
+do if [ ! -f "out.$i" -a ! -f "err.$i" ]
    then echo "Can't run test on $i, no output file!"
-   else
-     echo -n $i
-     ../compn $i
-     nasm -f elf64 out.s
-     cc -no-pie -o out out.o ../lib/printint.c
-     ./out > trial.$i
-     cmp -s "out.$i" "trial.$i"
-     if [ "$?" -eq "1" ]
-     then echo ": failed"
-       diff -c "out.$i" "trial.$i"
-       echo
-     else echo ": OK"
+
+   # Output file: compile the source, run it and
+   # capture the output, and compare it against
+   # the known-good output
+   else if [ -f "out.$i" ]
+        then
+	  # Print the test name, compile it
+	  # with our compiler
+          echo -n $i
+          ../compn -o out $i
+          ./out > trial.$i
+
+  	  # Compare this agains the correct output
+          cmp -s "out.$i" "trial.$i"
+
+	  # If different, announce failure
+          # and print out the difference
+          if [ "$?" -eq "1" ]
+          then echo ": failed"
+            diff -c "out.$i" "trial.$i"
+            echo
+
+	  # No failure, so announce success
+          else echo ": OK"
+          fi
+
+   # Error file: compile the source and
+   # capture the error messages. Compare
+   # against the known-bad output. Same
+   # mechanism as before
+   else if [ -f "err.$i" ]
+        then
+          echo -n $i
+          ../compn $i 2> "trial.$i"
+          cmp -s "err.$i" "trial.$i"
+          if [ "$?" -eq "1" ]
+          then echo ": failed"
+            diff -c "err.$i" "trial.$i"
+            echo
+          else echo ": OK"
+          fi
+        fi
      fi
-     rm -f out out.o out.s "trial.$i"
    fi
+   rm -f out out.o out.s "trial.$i"
 done
